export const posts = [
  {
    slug: 'fleet-architecture',
    title: 'The OpenSIN Fleet Architecture: 100+ Autonomous Agents',
    date: '2026-03-15',
    excerpt: 'How we built the first open-source AI agent fleet with 100+ specialized agents working 24/7.',
    tags: ['Architecture', 'Agents'],
    url: '/post/fleet-architecture/',
  },
  {
    slug: 'a2a-protocol',
    title: 'A2A Protocol: The Open Standard for Agent-to-Agent Communication',
    date: '2026-03-12',
    excerpt: 'Deep dive into the Agent-to-Agent protocol that lets AI agents delegate work without human mediation.',
    tags: ['Protocol', 'A2A'],
    url: '/post/a2a-protocol/',
  },
  {
    slug: 'security-architecture',
    title: 'Security Architecture: Zero Secrets in Code',
    date: '2026-03-08',
    excerpt: 'How OpenSIN ensures no API keys, tokens, or secrets ever touch the codebase.',
    tags: ['Security', 'Architecture'],
    url: '/post/security-architecture/',
  },
  {
    slug: 'oci-deployment',
    title: 'Deploying OpenSIN on Oracle Cloud Infrastructure (OCI)',
    date: '2026-03-05',
    excerpt: 'Step-by-step guide to deploying OpenSIN agents on OCI Always Free VMs for 24/7 operation.',
    tags: ['DevOps', 'OCI'],
    url: '/post/oci-deployment/',
  },
  {
    slug: 'cost-optimization',
    title: 'Cost Optimization: Running AI Agents for $0/month',
    date: '2026-03-01',
    excerpt: 'How we keep infrastructure costs at zero while running 100+ AI agents across multiple platforms.',
    tags: ['Infrastructure', 'Cost'],
    url: '/post/cost-optimization/',
  },
  {
    slug: 'team-orchestration',
    title: 'Team Orchestration: How 18 AI Teams Work Together',
    date: '2026-02-28',
    excerpt: 'The organizational structure behind OpenSIN — from coding to social media, all autonomous.',
    tags: ['Architecture', 'Teams'],
    url: '/post/team-orchestration/',
  },
  {
    slug: 'monitoring',
    title: 'Monitoring 100+ Agents: Observability at Fleet Scale',
    date: '2026-02-25',
    excerpt: 'Prometheus, Grafana, and structured logging — how we keep 100 agents healthy 24/7.',
    tags: ['Monitoring', 'DevOps'],
    url: '/post/monitoring/',
  },
  {
    slug: 'vs-competitors',
    title: 'OpenSIN vs OpenClaw vs Claude Code: Honest Comparison',
    date: '2026-02-20',
    excerpt: 'A feature-by-feature comparison of the top AI agent frameworks — no hype, just facts.',
    tags: ['Comparison', 'Analysis'],
    url: '/post/vs-competitors/',
  },
  {
    slug: 'model-routing',
    title: 'Intelligent Model Routing: Using the Right LLM for Each Task',
    date: '2026-02-15',
    excerpt: 'How OpenSIN agents automatically select the best LLM model based on task type and cost.',
    tags: ['LLM', 'Architecture'],
    url: '/post/model-routing/',
  },
  {
    slug: 'apple-ecosystem',
    title: 'OpenSIN in the Apple Ecosystem: macOS, iOS, and Beyond',
    date: '2026-02-10',
    excerpt: 'How OpenSIN agents integrate with macOS, iOS, Calendar, Messages, and the entire Apple ecosystem.',
    tags: ['Apple', 'Integration'],
    url: '/post/apple-ecosystem/',
  },
  {
    slug: 'ci-cd',
    title: 'CI/CD for AI Agents: Automated Testing and Deployment',
    date: '2026-02-05',
    excerpt: 'How we automated the entire build-test-deploy pipeline for 100+ AI agents.',
    tags: ['CI/CD', 'DevOps'],
    url: '/post/ci-cd/',
  },
  {
    slug: 'agent-forge',
    title: 'Agent Forge: Creating New AI Agents in Minutes',
    date: '2026-02-01',
    excerpt: 'The OpenSIN Agent Forge skill that lets you scaffold, configure, and deploy a new agent in under 10 minutes.',
    tags: ['Developer Experience', 'Agents'],
    url: '/post/agent-forge/',
  },
  {
    slug: 'self-healing',
    title: 'Self-Healing Fleet: How OpenSIN Recovers from Failures Automatically',
    date: '2026-01-28',
    excerpt: 'The self-healing architecture that keeps 100+ agents running 24/7 without human intervention.',
    tags: ['Architecture', 'Reliability'],
    url: '/post/self-healing/',
  },
  {
    slug: 'n8n-integration',
    title: 'n8n Integration: The Router Behind the OpenSIN Fleet',
    date: '2026-01-25',
    excerpt: 'How we use n8n as the indestructible "dumb" router for all inbound work and webhook processing.',
    tags: ['n8n', 'Architecture'],
    url: '/post/n8n-integration/',
  },
  {
    slug: 'supabase',
    title: 'Supabase: The Central Database for the Agent Fleet',
    date: '2026-01-20',
    excerpt: 'How we use Supabase as the single source of truth for agent state, tokens, and fleet management.',
    tags: ['Database', 'Supabase'],
    url: '/post/supabase/',
  },
  {
    slug: 'future-vision',
    title: 'The Future of OpenSIN: Where We Are Going in 2026',
    date: '2026-01-15',
    excerpt: 'Our vision for the next 12 months: enterprise features, marketplace, and true AI autonomy.',
    tags: ['Vision', 'Roadmap'],
    url: '/post/future-vision/',
  },
]

export default {
  load() {
    return {
      posts,
    }
  },
}
